package Funfhmmer::Scorecons;

=head1 NAME

Funfhmmer::Scorecons - object to generate Scorecons and DOPS files for cluster alignment files

=head1 SYNOPSIS

	use Funfhmmer::Scorecons

=head1 DESCRIPTION

This is used to generate Scorecons and DOPS files for sequence cluster alignment files.
Scorecons (Valdar, 2000) is used to identify residue alignment columns in an alignment that are highly conserved.
DOPS score, also generated by Scorecons, gives a measure of the diversity of sequences present (information content) in a sequence alignment file.
Alignments with high DOPS are considered to have high information content and are useful (informative) for sequence analysis methods such as conservation analysis.

=cut

use strict;
use warnings;

# core modules
use FindBin;
FindBin::again();
use Exporter qw(import);

# non-core modules
use Path::Tiny;

# Funfhmmer modules
use lib "$FindBin::Bin/../lib";

our $bindir = path($FindBin::Bin, "..", "bin");

our @EXPORT_OK = qw(calculate_scorecons_dops assign_dops_score);

=head1 METHODS

=head2 calculate_scorecons_dops()

...

	calculate_scorecons_dops( $cluster_name, $dir)

=cut

sub calculate_scorecons_dops{

	my ($cluster_name, $funfam_dir) = @_;
	my $analysis_subfoldername = "analysis_data";
	my $cluster_dopsfile= path("$funfam_dir/$analysis_subfoldername","$cluster_name.aln.dops");
	
	unless($cluster_dopsfile->exists){
	
		if(path("$funfam_dir", "$cluster_name.aln")->exists){
		
			system "$bindir/scorecons/scorecons -a $funfam_dir/$cluster_name.aln -o $funfam_dir/$analysis_subfoldername/$cluster_name.aln.scorecons -m $bindir/scorecons/PET91mod.mat2 1> $cluster_dopsfile 2> $dir/$analysis_subfoldername/funfhmmer_run_dops.temp";
			
			unlink("$funfam_dir/$analysis_subfoldername/$cluster_name.aln.scorecons"); 
			
			#Edit the dops file to replace the file from "DOPS score: xxx" to just "xxx"
			system("perl -p -i -e 's/DOPS score: //g' $cluster_dopsfile");
		}
		
		elsif(-e "$funfam_dir/$analysis_subfoldername/$cluster_name.aln"){
			
			system "$bindir/scorecons/scorecons -a $funfam_dir/$analysis_subfoldername/$cluster_name.aln -o $funfam_dir/$analysis_subfoldername/$cluster_name.aln.scorecons -m $bindir/scorecons/PET91mod.mat2 1> $cluster_dopsfile 2> $funfam_dir/$analysis_subfoldername/funfhmmer_run_dops.temp";
			
			unlink("$funfam_dir/$analysis_subfoldername/$cluster_name.aln.scorecons");
			
			system("perl -p -i -e 's/DOPS score: //g' $cluster_dopsfile");
		}
	}
}

=head2 assign_dops_score()

...

	assign_dops_score( $cluster_name, $dir)

=cut

sub assign_dops_score{
	my ($cluster_name, $funfam_dir) = @_;
	my $analysis_subfoldername = "analysis_data";
	my $dops_file = path("$funfam_dir/$analysis_subfoldername","$cluster_name.aln.dops");
	
	unless(-e "$dops_file"){
		&calculate_scorecons_dops($cluster_name, "$funfam_dir");
	}
	my $dops_score;
	if(-z "$dops_file"){
		$dops_score= "0.000";
	}
	elsif(-e "$dops_file"){
		my @dops_lines = path("$dops_file")->lines;
		$dops_score=$dops_lines[0];
		chomp($dops_score);
	}
	return $dops_score;
}

1;
